/* GENERATED by scripts/build-browser-engine.ts — do not edit.
 * Serialized from config/*.yaml so the browser bundle cannot drift from
 * the committed configuration. Re-run the build after any config change. */
import type { SystemConfig } from '../schemas/config.js';

export const CONFIG: SystemConfig = {
  "capabilities": {
    "capabilities": {
      "strategy": {
        "description": "Company direction, positioning, major business choices",
        "business_area": "strategy",
        "specialist_only": false
      },
      "project_management": {
        "description": "Tracking work, chasing dependencies, keeping things from falling through",
        "business_area": "operations",
        "specialist_only": false
      },
      "research": {
        "description": "Gathering information, comparing options, assembling inputs for a decision",
        "business_area": "general",
        "specialist_only": false
      },
      "coordination": {
        "description": "Scheduling, organizing, aligning multiple parties",
        "business_area": "operations",
        "specialist_only": false
      },
      "follow_up": {
        "description": "Chasing outstanding items until they arrive",
        "business_area": "operations",
        "specialist_only": false
      },
      "administration": {
        "description": "Forms, paperwork, document collection, routine business tasks",
        "business_area": "operations",
        "specialist_only": false
      },
      "vendor_coordination": {
        "description": "Working with vendors on logistics, documents, scheduling",
        "business_area": "operations",
        "specialist_only": false
      },
      "retail": {
        "description": "Retailer relationships, onboarding, buyer communication",
        "business_area": "retail",
        "specialist_only": false
      },
      "podcast_advertising": {
        "description": "Podcast ad placements, sourcing, campaign coordination",
        "business_area": "marketing",
        "specialist_only": false
      },
      "paid_media": {
        "description": "Google, Bing, Amazon paid advertising management and optimization",
        "business_area": "marketing",
        "specialist_only": true
      },
      "organic_social": {
        "description": "Organic social content, posting, content calendar",
        "business_area": "marketing",
        "specialist_only": true
      },
      "content_creation": {
        "description": "Video, photo, written content production",
        "business_area": "marketing",
        "specialist_only": true
      },
      "graphic_design": {
        "description": "Visual assets, mockups, creative deliverables",
        "business_area": "design",
        "specialist_only": true
      },
      "packaging_design": {
        "description": "Packaging artwork, dielines, packaging updates",
        "business_area": "design",
        "specialist_only": true
      },
      "copywriting": {
        "description": "Marketing copy, website copy, email copy",
        "business_area": "marketing",
        "specialist_only": false
      },
      "manufacturing": {
        "description": "Production runs, manufacturer coordination, formulation execution",
        "business_area": "operations",
        "specialist_only": true
      },
      "inventory": {
        "description": "Stock levels, forecasting, replenishment",
        "business_area": "operations",
        "specialist_only": true
      },
      "production": {
        "description": "Production planning and scheduling",
        "business_area": "operations",
        "specialist_only": true
      },
      "supply_chain": {
        "description": "Sourcing, components, supplier management",
        "business_area": "operations",
        "specialist_only": true
      },
      "logistics": {
        "description": "Shipping, freight, 3PL, fulfillment operations",
        "business_area": "operations",
        "specialist_only": true
      },
      "fulfillment": {
        "description": "Order fulfillment execution and exceptions",
        "business_area": "operations",
        "specialist_only": true
      },
      "website": {
        "description": "Website changes, ecommerce storefront, site content implementation",
        "business_area": "technology",
        "specialist_only": true
      },
      "technical": {
        "description": "Technical implementation, systems, infrastructure",
        "business_area": "technology",
        "specialist_only": true
      },
      "integrations": {
        "description": "System integrations, APIs, data flow between tools",
        "business_area": "technology",
        "specialist_only": true
      },
      "finance": {
        "description": "Financial decisions, cash management, financial strategy",
        "business_area": "finance",
        "specialist_only": false
      },
      "accounts_payable": {
        "description": "Invoice processing and vendor payment execution",
        "business_area": "finance",
        "specialist_only": true
      },
      "invoice_payments": {
        "description": "Executing payments against approved invoices",
        "business_area": "finance",
        "specialist_only": true
      },
      "bookkeeping": {
        "description": "Books, reconciliations, recurring financial management",
        "business_area": "finance",
        "specialist_only": true
      },
      "financial_reporting": {
        "description": "Financial reports, weekly financials, statements",
        "business_area": "finance",
        "specialist_only": true
      },
      "customer_service": {
        "description": "Customer inquiries, issues, support",
        "business_area": "customer",
        "specialist_only": true
      },
      "customer_feedback": {
        "description": "Aggregating and interpreting customer sentiment and complaints",
        "business_area": "customer",
        "specialist_only": false
      },
      "research_grants": {
        "description": "Research partnerships, grants, scientific collaboration",
        "business_area": "research",
        "specialist_only": false
      },
      "analytics": {
        "description": "Business analytics, performance measurement, reporting",
        "business_area": "analytics",
        "specialist_only": false
      },
      "operations": {
        "description": "General operational ownership and troubleshooting",
        "business_area": "operations",
        "specialist_only": false
      },
      "partnerships": {
        "description": "Business development, partnership sourcing and negotiation",
        "business_area": "business_development",
        "specialist_only": false
      },
      "negotiation": {
        "description": "Commercial negotiation on pricing and terms",
        "business_area": "business_development",
        "specialist_only": false
      },
      "legal_coordination": {
        "description": "Coordinating with counsel; contract routing (never legal advice)",
        "business_area": "legal",
        "specialist_only": false
      },
      "interview_support": {
        "description": "Podcast and interview subject-matter participation",
        "business_area": "marketing",
        "specialist_only": true
      },
      "product": {
        "description": "Product decisions, formulation direction, roadmap",
        "business_area": "product",
        "specialist_only": false
      },
      "hiring": {
        "description": "Hiring, contractor selection, team decisions",
        "business_area": "people",
        "specialist_only": false
      }
    }
  },
  "people": {
    "people": {
      "adi": {
        "name": "Adi",
        "role": "CEO",
        "internal": true,
        "discovery_status": "confirmed",
        "importance": 5,
        "decision_authority": "high",
        "broad_generalist": true,
        "eligible_for_all_areas": true,
        "leverage_candidate": false,
        "aliases": [
          "Adi Malik"
        ],
        "capabilities": {
          "strategy": {
            "confidence": 0.98,
            "proficiency": 0.95,
            "level": "primary",
            "confirmed": true
          },
          "partnerships": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "negotiation": {
            "confidence": 0.93,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "podcast_advertising": {
            "confidence": 0.9,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          },
          "retail": {
            "confidence": 0.88,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          },
          "product": {
            "confidence": 0.88,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          },
          "finance": {
            "confidence": 0.85,
            "proficiency": 0.8,
            "level": "primary",
            "confirmed": true
          },
          "copywriting": {
            "confidence": 0.8,
            "proficiency": 0.8,
            "level": "secondary",
            "confirmed": true
          },
          "paid_media": {
            "confidence": 0.75,
            "proficiency": 0.7,
            "level": "secondary",
            "confirmed": true
          },
          "analytics": {
            "confidence": 0.78,
            "proficiency": 0.75,
            "level": "secondary",
            "confirmed": true
          },
          "research_grants": {
            "confidence": 0.75,
            "proficiency": 0.7,
            "level": "secondary",
            "confirmed": true
          },
          "legal_coordination": {
            "confidence": 0.8,
            "proficiency": 0.7,
            "level": "primary",
            "confirmed": true
          },
          "hiring": {
            "confidence": 0.85,
            "proficiency": 0.8,
            "level": "primary",
            "confirmed": true
          },
          "website": {
            "confidence": 0.6,
            "proficiency": 0.55,
            "level": "secondary",
            "confirmed": true
          },
          "operations": {
            "confidence": 0.65,
            "proficiency": 0.65,
            "level": "secondary",
            "confirmed": true
          },
          "vendor_coordination": {
            "confidence": 0.7,
            "proficiency": 0.7,
            "level": "secondary",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Hands-on CEO who performs work across essentially all areas.",
          "Do not limit routing based on CEO title.",
          "Optimize to protect attention without preventing hands-on ownership.",
          "CEO dependency is not the same as CEO ownership -- always state the mode."
        ],
        "email": "adi@120life.com",
        "slack_user_id": "UFAMJBSRL"
      },
      "paul": {
        "name": "Paul",
        "role": "Executive Assistant / Project Manager",
        "internal": true,
        "discovery_status": "confirmed",
        "importance": 5,
        "decision_authority": "low",
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": true,
        "aliases": [],
        "capabilities": {
          "project_management": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "coordination": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "follow_up": {
            "confidence": 0.95,
            "proficiency": 0.92,
            "level": "primary",
            "confirmed": true
          },
          "administration": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "research": {
            "confidence": 0.88,
            "proficiency": 0.82,
            "level": "primary",
            "confirmed": true
          },
          "vendor_coordination": {
            "confidence": 0.9,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          },
          "retail": {
            "confidence": 0.75,
            "proficiency": 0.72,
            "level": "secondary",
            "confirmed": true
          },
          "operations": {
            "confidence": 0.7,
            "proficiency": 0.68,
            "level": "secondary",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Highly capable virtual assistant; functions well beyond admin support.",
          "Often appropriate for cross-functional execution and tracking.",
          "Consider as project manager even when a specialist owns the task.",
          "Do not overload indiscriminately -- weigh workload and complexity."
        ],
        "slack_user_id": "U054X7JDN1Z"
      },
      "mike": {
        "name": "Mike",
        "role": "COO / CTO",
        "internal": true,
        "discovery_status": "confirmed",
        "importance": 5,
        "decision_authority": "high",
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [
          "Michaelhammersley",
          "michaelhammersley",
          "Michael Hammersley",
          "Mike Hammersley",
          "Michael Hammersley"
        ],
        "capabilities": {
          "operations": {
            "confidence": 0.95,
            "proficiency": 0.92,
            "level": "primary",
            "confirmed": true
          },
          "supply_chain": {
            "confidence": 0.93,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "manufacturing": {
            "confidence": 0.93,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "inventory": {
            "confidence": 0.92,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "production": {
            "confidence": 0.92,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "logistics": {
            "confidence": 0.9,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": true
          },
          "fulfillment": {
            "confidence": 0.88,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          },
          "website": {
            "confidence": 0.9,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          },
          "technical": {
            "confidence": 0.92,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": true
          },
          "integrations": {
            "confidence": 0.9,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          },
          "vendor_coordination": {
            "confidence": 0.82,
            "proficiency": 0.8,
            "level": "secondary",
            "confirmed": true
          },
          "product": {
            "confidence": 0.75,
            "proficiency": 0.75,
            "level": "secondary",
            "confirmed": true
          },
          "analytics": {
            "confidence": 0.65,
            "proficiency": 0.65,
            "level": "secondary",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Do not classify as only operations or only technology.",
          "Adi may make the decision while Mike owns execution."
        ],
        "email": "mike@120life.com",
        "slack_user_id": "U01P8MKBM60"
      },
      "ira": {
        "name": "Ira",
        "role": "Customer Service",
        "internal": true,
        "discovery_status": "confirmed",
        "importance": 3,
        "decision_authority": "low",
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [
          "Ira Antelis"
        ],
        "capabilities": {
          "customer_service": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "customer_feedback": {
            "confidence": 0.85,
            "proficiency": 0.8,
            "level": "primary",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Customer-service trends should generate business signals, not a task per ticket.",
          "Do not route customer-originated strategic decisions to Ira by default."
        ],
        "email": "ira@120life.com"
      },
      "peter": {
        "name": "Peter",
        "role": "Accounts Payable",
        "internal": true,
        "discovery_status": "confirmed",
        "importance": 3,
        "decision_authority": "low",
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [
          "Peter Levy"
        ],
        "capabilities": {
          "accounts_payable": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "invoice_payments": {
            "confidence": 0.95,
            "proficiency": 0.92,
            "level": "primary",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Peter handles invoice/payment EXECUTION.",
          "He is not the owner of financial analysis. Do not conflate with Brian."
        ]
      },
      "brian": {
        "name": "Brian",
        "role": "Bookkeeping / Financials",
        "internal": true,
        "discovery_status": "confirmed",
        "importance": 3,
        "decision_authority": "low",
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [
          "Brian Ouellette"
        ],
        "capabilities": {
          "bookkeeping": {
            "confidence": 0.95,
            "proficiency": 0.92,
            "level": "primary",
            "confirmed": true
          },
          "financial_reporting": {
            "confidence": 0.92,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": true
          },
          "analytics": {
            "confidence": 0.6,
            "proficiency": 0.6,
            "level": "secondary",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Brian handles bookkeeping and recurring financial management.",
          "Do not route invoice payment to Brian; that is Peter."
        ]
      },
      "buster": {
        "name": "Buster",
        "role": "Organic Social",
        "internal": false,
        "relationship_type": "contractor",
        "discovery_status": "confirmed",
        "importance": 3,
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [],
        "capabilities": {
          "organic_social": {
            "confidence": 0.92,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": true
          },
          "content_creation": {
            "confidence": 0.9,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          }
        },
        "collaborates_with": [
          "chase"
        ],
        "notes": []
      },
      "chase": {
        "name": "Chase",
        "role": "Organic Social",
        "internal": false,
        "relationship_type": "contractor",
        "discovery_status": "confirmed",
        "importance": 3,
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [
          "Chase Dinning"
        ],
        "capabilities": {
          "organic_social": {
            "confidence": 0.92,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": true
          },
          "content_creation": {
            "confidence": 0.9,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": true
          }
        },
        "collaborates_with": [
          "buster"
        ],
        "notes": []
      },
      "julienne": {
        "name": "Julienne",
        "role": "Designer",
        "internal": false,
        "relationship_type": "contractor",
        "discovery_status": "confirmed",
        "importance": 3,
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [],
        "capabilities": {
          "packaging_design": {
            "confidence": 0.93,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "graphic_design": {
            "confidence": 0.92,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": true
          },
          "content_creation": {
            "confidence": 0.65,
            "proficiency": 0.65,
            "level": "secondary",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Paul often coordinates delivery; Adi often approves."
        ]
      },
      "susan": {
        "name": "Susan",
        "role": "Podcast / Interview Support",
        "internal": false,
        "relationship_type": "contractor",
        "discovery_status": "confirmed",
        "importance": 2,
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [
          "Susan Schachter"
        ],
        "capabilities": {
          "interview_support": {
            "confidence": 0.85,
            "proficiency": 0.85,
            "level": "occasional",
            "confirmed": true
          }
        },
        "collaborates_with": [],
        "notes": [
          "Involved selectively, NOT the default podcast owner.",
          "Include only when correspondence indicates an interview needs her."
        ]
      },
      "rob": {
        "name": "Rob",
        "role": "Unknown",
        "internal": true,
        "discovery_status": "discovered",
        "importance": 2,
        "broad_generalist": false,
        "eligible_for_all_areas": false,
        "leverage_candidate": false,
        "aliases": [],
        "capabilities": {},
        "collaborates_with": [],
        "notes": [
          "Discovered in the Slack directory on 2026-08-25; function not yet established."
        ],
        "email": "rob@120life.com",
        "slack_user_id": "U0A3XU3EXKP"
      }
    }
  },
  "organizations": {
    "organizations": {
      "one_twenty_life": {
        "name": "120/Life",
        "type": "internal",
        "importance": 5,
        "domains": [],
        "capabilities": [],
        "notes": []
      },
      "radioactive_media": {
        "name": "RadioActive Media",
        "type": "agency",
        "importance": 4,
        "domains": [],
        "relationship_owner": "adi",
        "execution_tracker": "paul",
        "capabilities": {
          "podcast_sourcing": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": false
          },
          "podcast_placement": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": false
          },
          "podcast_campaign_execution": {
            "confidence": 0.92,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": false
          },
          "podcast_advertising": {
            "confidence": 0.95,
            "proficiency": 0.9,
            "level": "primary",
            "confirmed": false
          }
        },
        "notes": [
          "Sources podcast opportunities, coordinates placements, quotes pricing.",
          "Adi decides whether an opportunity is attractive; RadioActive executes.",
          "Paul tracks required materials and deadlines.",
          "Susan may participate if a specific interview requires her."
        ]
      },
      "quartile": {
        "name": "Quartile",
        "type": "agency",
        "importance": 4,
        "domains": [],
        "relationship_owner": "adi",
        "execution_tracker": "paul",
        "capabilities": {
          "paid_media": {
            "confidence": 0.95,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": false
          },
          "google_ads": {
            "confidence": 0.95,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": false
          },
          "bing_ads": {
            "confidence": 0.9,
            "proficiency": 0.85,
            "level": "primary",
            "confirmed": false
          },
          "amazon_ads": {
            "confidence": 0.93,
            "proficiency": 0.88,
            "level": "primary",
            "confirmed": false
          },
          "analytics": {
            "confidence": 0.75,
            "proficiency": 0.75,
            "level": "secondary",
            "confirmed": false
          }
        },
        "notes": [
          "External execution partner for paid digital advertising.",
          "Owns investigation of paid-media performance changes.",
          "Adi receives only material recommendations and decisions.",
          "Paul may track the response."
        ]
      }
    },
    "organization_types": [
      "internal",
      "agency",
      "vendor",
      "retailer",
      "manufacturer",
      "media_partner",
      "research_partner",
      "professional_services",
      "financial",
      "logistics",
      "customer",
      "other"
    ],
    "generic_email_domains": [
      "gmail.com",
      "googlemail.com",
      "yahoo.com",
      "outlook.com",
      "hotmail.com",
      "live.com",
      "icloud.com",
      "me.com",
      "aol.com",
      "proton.me",
      "protonmail.com",
      "msn.com"
    ],
    "noreply_patterns": [
      "noreply@",
      "no-reply@",
      "donotreply@",
      "do-not-reply@",
      "notifications@",
      "mailer-daemon@",
      "bounce",
      "postmaster@",
      "automated@",
      "alerts@"
    ]
  },
  "businessAreas": {
    "business_areas": {
      "strategy": {
        "description": "Company direction, positioning, major business choices",
        "default_capabilities": [
          "strategy"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "marketing": {
        "description": "Paid media, podcast advertising, organic social, email, content",
        "default_capabilities": [
          "paid_media",
          "podcast_advertising",
          "organic_social",
          "copywriting"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "retail": {
        "description": "Retailer relationships, onboarding, distribution",
        "default_capabilities": [
          "retail",
          "administration",
          "vendor_coordination"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "operations": {
        "description": "Supply chain, manufacturing, inventory, logistics, fulfillment",
        "default_capabilities": [
          "operations",
          "supply_chain",
          "manufacturing",
          "inventory",
          "logistics"
        ],
        "typical_decision_maker": "mike",
        "escalate_to_ceo_when": [
          "material spend",
          "production timing risk",
          "supply disruption"
        ],
        "aggregate_signals": false
      },
      "product": {
        "description": "Product decisions, formulation, packaging direction",
        "default_capabilities": [
          "product",
          "packaging_design",
          "manufacturing"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "technology": {
        "description": "Website, integrations, technical systems",
        "default_capabilities": [
          "website",
          "technical",
          "integrations"
        ],
        "typical_decision_maker": "mike",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "finance": {
        "description": "Cash, payments, bookkeeping, financial reporting",
        "default_capabilities": [
          "finance",
          "accounts_payable",
          "bookkeeping",
          "financial_reporting"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false,
        "routing_note": "Never route by 'financial' alone; distinguish payment execution from bookkeeping from decision."
      },
      "customer": {
        "description": "Customer service, customer experience, feedback",
        "default_capabilities": [
          "customer_service",
          "customer_feedback"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": true
      },
      "design": {
        "description": "Packaging, creative assets, mockups",
        "default_capabilities": [
          "packaging_design",
          "graphic_design"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "business_development": {
        "description": "Partnerships, new channels, business development",
        "default_capabilities": [
          "partnerships",
          "negotiation"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "research": {
        "description": "Research partnerships, grants, scientific work",
        "default_capabilities": [
          "research_grants",
          "research"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "legal": {
        "description": "Contracts, regulatory, counsel coordination",
        "default_capabilities": [
          "legal_coordination"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false,
        "approval_class": "RED"
      },
      "people": {
        "description": "Hiring, contractors, team",
        "default_capabilities": [
          "hiring"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false,
        "approval_class": "RED"
      },
      "analytics": {
        "description": "Performance measurement, reporting, business analytics",
        "default_capabilities": [
          "analytics"
        ],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      },
      "general": {
        "description": "Uncategorized",
        "default_capabilities": [],
        "typical_decision_maker": "adi",
        "escalate_to_ceo_when": [],
        "aggregate_signals": false
      }
    }
  },
  "priorityRules": {
    "weights": {
      "impact": 3,
      "urgency": 3,
      "risk": 2,
      "relationship": 1,
      "strategic_importance": 1,
      "blocker": 1,
      "decision_dependency": 1,
      "effort_penalty": 0.5
    },
    "bonuses": {
      "blocks_other_tasks_each": 1.5,
      "blocks_other_tasks_cap": 6,
      "decision_ready_bonus": 3,
      "approve_only_bonus": 2,
      "we_owe_external_bonus": 2,
      "deadline_bonus": {
        "overdue": 8,
        "within_24h": 6,
        "within_3d": 4,
        "within_7d": 2,
        "within_14d": 1,
        "beyond": 0
      }
    },
    "penalties": {
      "stale_days_threshold": 14,
      "stale_penalty": 2,
      "unconfirmed_proposal_penalty": 1.5,
      "low_confidence_threshold": 0.6,
      "low_confidence_penalty": 2,
      "waiting_external_penalty": 1,
      "waiting_internal_penalty": 0.5
    },
    "signal_multipliers": {
      "cash_risk": 1.35,
      "inventory_risk": 1.3,
      "production_risk": 1.3,
      "supply_disruption": 1.3,
      "compliance_risk": 1.4,
      "revenue_opportunity": 1.15,
      "roas_decline": 1.15,
      "customer_experience": 1.1
    },
    "compound_rules": [
      {
        "name": "production_payment_and_low_inventory",
        "when": {
          "all": [
            {
              "signal": "cash_risk"
            },
            {
              "signal": "inventory_risk"
            }
          ]
        },
        "multiplier": 1.6,
        "reason": "Production payment timing coincides with low inventory coverage."
      },
      {
        "name": "external_overdue_on_critical_path",
        "when": {
          "all": [
            {
              "waiting_external_days_gte": 3
            },
            {
              "blocks_other_tasks_gte": 1
            }
          ]
        },
        "bonus": 4,
        "reason": "An external party is overdue and other work depends on it."
      },
      {
        "name": "decision_blocking_specialist",
        "when": {
          "all": [
            {
              "ceo_action_mode_in": [
                "DECIDE",
                "APPROVE"
              ]
            },
            {
              "blocks_other_tasks_gte": 1
            }
          ]
        },
        "bonus": 3,
        "reason": "A short CEO decision is holding up someone else's execution."
      }
    ],
    "ranking": {
      "brief_inclusion_floor": 8,
      "material_rank_change": 3,
      "material_score_change": 1.5,
      "daily_brief": {
        "ceo_top_n": 5,
        "paul_can_take_n": 5,
        "decisions_n": 5,
        "waiting_on_n": 8,
        "risks_n": 3,
        "opportunities_n": 3
      }
    },
    "portfolio_review": {
      "max_ai_adjustment_ratio": 0.35,
      "run_schedule": "0 5 * * 1-5",
      "min_tasks_to_review": 5
    }
  },
  "routingRules": {
    "engine_version": "1.0.0",
    "scoring": {
      "capability_match": 4,
      "primary_capability_bonus": 1.5,
      "continuity_bonus": 3,
      "relationship_owner_bonus": 2.5,
      "recent_involvement_bonus": 1.5,
      "specialist_required_bonus": 2,
      "workload_penalty_per_open_task": 0.15,
      "workload_penalty_cap": 3,
      "overdue_penalty_per_task": 0.35,
      "overdue_penalty_cap": 3,
      "handoff_friction_penalty": 1,
      "min_gain_to_reassign": 2,
      "provisional_person_penalty": 4,
      "external_person_penalty": 2
    },
    "ceo": {
      "person": "adi",
      "eligible_for_all_areas": true,
      "requires_ceo_when": [
        {
          "spend_above": 5000
        },
        {
          "contract_or_legal": true
        },
        {
          "investor_related": true
        },
        {
          "hiring_or_termination": true
        },
        {
          "pricing_or_offer_change": true
        },
        {
          "partnership_commitment": true
        },
        {
          "public_or_reputational": true
        },
        {
          "strategic_direction": true
        }
      ],
      "reconsider_ceo_attribution_when": [
        {
          "task_is_information_gathering": true
        },
        {
          "task_is_document_collection": true
        },
        {
          "task_is_scheduling": true
        },
        {
          "task_is_routine_vendor_followup": true
        },
        {
          "task_is_status_chasing": true
        },
        {
          "task_is_administrative": true
        }
      ],
      "brief_dependency_floor": 2
    },
    "leverage": {
      "person": "paul",
      "can_own_capabilities": [
        "project_management",
        "coordination",
        "follow_up",
        "administration",
        "research",
        "vendor_coordination",
        "retail"
      ],
      "can_project_manage_when_specialist_owns": true,
      "never_owner_of_capabilities": [
        "manufacturing",
        "production",
        "supply_chain",
        "inventory",
        "logistics",
        "fulfillment",
        "technical",
        "integrations",
        "website",
        "accounts_payable",
        "invoice_payments",
        "bookkeeping",
        "financial_reporting",
        "paid_media",
        "packaging_design",
        "graphic_design",
        "organic_social",
        "customer_service"
      ],
      "do_not_duplicate": [
        {
          "capability": "invoice_payments",
          "reason": "Peter executes payments; a parallel Paul task adds no value."
        },
        {
          "capability": "bookkeeping",
          "reason": "Brian owns the books; coordination adds friction, not leverage."
        },
        {
          "capability": "customer_service",
          "reason": "Ira handles tickets directly."
        }
      ],
      "max_open_tasks_soft": 25,
      "max_open_tasks_hard": 40,
      "min_leverage_value": 1
    },
    "hints": [
      {
        "name": "invoice_payment_to_ap",
        "match": {
          "any_keyword": [
            "invoice",
            "bill payment",
            "remittance",
            "pay the vendor",
            "past due invoice",
            "w-9",
            "ach details"
          ],
          "not_keyword": [
            "reconcile",
            "reconciliation",
            "bookkeeping",
            "books",
            "ledger",
            "close the month"
          ]
        },
        "required_capabilities": [
          "invoice_payments"
        ],
        "decision_required": false,
        "aggregate_as_signal": false,
        "reason": "Invoice/payment execution belongs to accounts payable, not bookkeeping."
      },
      {
        "name": "bookkeeping_discrepancy_to_bookkeeper",
        "match": {
          "any_keyword": [
            "reconcile",
            "reconciliation",
            "bookkeeping",
            "books",
            "ledger",
            "discrepancy",
            "month-end",
            "financial statement",
            "p&l",
            "balance sheet"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "bookkeeping"
        ],
        "decision_required": false,
        "aggregate_as_signal": false,
        "reason": "Bookkeeping and reconciliation belong to the bookkeeper, not accounts payable."
      },
      {
        "name": "paid_media_to_agency",
        "match": {
          "any_keyword": [
            "roas",
            "google ads",
            "bing",
            "amazon ads",
            "cpc",
            "ad spend",
            "campaign performance",
            "acos"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "paid_media"
        ],
        "external_organization_capability": "paid_media",
        "decision_required": false,
        "aggregate_as_signal": false,
        "reason": "Paid-media investigation is owned by the external agency partner."
      },
      {
        "name": "podcast_opportunity",
        "match": {
          "any_keyword": [
            "podcast",
            "episode sponsorship",
            "host read",
            "rate card",
            "podcast placement"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "podcast_advertising"
        ],
        "external_organization_capability": "podcast_sourcing",
        "decision_required": true,
        "aggregate_as_signal": false,
        "reason": "Podcast sourcing sits with the media partner; the spend decision sits with the CEO."
      },
      {
        "name": "production_and_supply",
        "match": {
          "any_keyword": [
            "production run",
            "manufacturer",
            "co-packer",
            "batch",
            "formulation",
            "lead time",
            "raw material",
            "coa",
            "certificate of analysis"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "manufacturing",
          "production",
          "supply_chain"
        ],
        "decision_required": false,
        "aggregate_as_signal": false,
        "reason": "Manufacturing and supply matters require operational ownership."
      },
      {
        "name": "inventory",
        "match": {
          "any_keyword": [
            "inventory",
            "stock level",
            "out of stock",
            "reorder",
            "forecast",
            "replenish",
            "safety stock"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "inventory"
        ],
        "decision_required": false,
        "aggregate_as_signal": false,
        "reason": "Inventory matters require operational ownership."
      },
      {
        "name": "website_and_technical",
        "match": {
          "any_keyword": [
            "website",
            "shopify",
            "landing page",
            "checkout",
            "integration",
            "api",
            "site speed",
            "404",
            "subscription flow"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "website",
          "technical"
        ],
        "decision_required": false,
        "aggregate_as_signal": false,
        "reason": "Website and technical implementation require technical ownership."
      },
      {
        "name": "retailer_onboarding",
        "match": {
          "any_keyword": [
            "vendor form",
            "onboarding packet",
            "retailer portal",
            "new vendor setup",
            "vendor agreement",
            "edi",
            "item setup"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "administration",
          "retail",
          "coordination"
        ],
        "decision_required": false,
        "aggregate_as_signal": false,
        "leverage_hint": "PAUL_CAN_OWN",
        "reason": "Retail onboarding paperwork is coordination work, not CEO work."
      },
      {
        "name": "packaging_design",
        "match": {
          "any_keyword": [
            "packaging",
            "label",
            "dieline",
            "mockup",
            "artwork",
            "carton"
          ],
          "not_keyword": []
        },
        "required_capabilities": [
          "packaging_design"
        ],
        "decision_required": false,
        "aggregate_as_signal": false,
        "reason": "Packaging artwork requires design capability."
      },
      {
        "name": "customer_service_pattern",
        "match": {
          "any_keyword": [
            "customers keep",
            "multiple customers",
            "recurring complaint",
            "support trend",
            "customers report"
          ],
          "not_keyword": []
        },
        "required_capabilities": [],
        "decision_required": false,
        "aggregate_as_signal": true,
        "reason": "Customer-service patterns are business signals, not individual tickets."
      }
    ],
    "evidence_thresholds": {
      "create_provisional_person": 1,
      "promote_to_provisional": 2,
      "promote_to_confirmed": 6,
      "confirmed_requires_days": 14,
      "capability_edge_create": 2,
      "capability_edge_strengthen": 1,
      "reassign_low_impact_confidence": 0.65,
      "reassign_high_impact_confidence": 0.85,
      "high_impact_when_priority_above": 20,
      "min_routing_confidence": 0.45
    },
    "decay": {
      "half_life_days": 180,
      "floor": 0.25,
      "exempt_manually_confirmed": true
    }
  },
  "approvalRules": {
    "global": {
      "external_sending_enabled": false,
      "draft_creation_enabled": false,
      "internal_slack_posting_enabled": true
    },
    "classes": {
      "GREEN": {
        "description": "Potentially automatable once reliability is demonstrated",
        "requires_human_approval": false,
        "never_automate": false,
        "phase_available_from": 10,
        "examples": [
          "Simple acknowledgment of a received document",
          "Scheduling logistics with an already-agreed party",
          "Routine internal reminder",
          "Request for information both sides already agreed to exchange"
        ],
        "applies_to": [],
        "conditions": [
          {
            "no_pricing_content": true
          },
          {
            "no_commitment_created": true
          },
          {
            "recipient_relationship_exists": true
          },
          {
            "value_at_stake_below": 1000
          }
        ]
      },
      "YELLOW": {
        "description": "Human approval required before anything leaves the building",
        "requires_human_approval": true,
        "never_automate": false,
        "phase_available_from": 6,
        "examples": [],
        "applies_to": [
          "vendors",
          "retailers",
          "agencies",
          "podcast_partners",
          "negotiations",
          "material_operational_messages",
          "pricing_discussions",
          "new_external_contacts",
          "anything_creating_a_commitment"
        ],
        "conditions": []
      },
      "RED": {
        "description": "Always manual. No draft is auto-sent, ever, under any policy.",
        "requires_human_approval": true,
        "never_automate": true,
        "phase_available_from": null,
        "examples": [],
        "applies_to": [
          "legal",
          "regulatory",
          "contracts",
          "employment",
          "investors",
          "health_or_product_claims",
          "disputes",
          "sensitive_finances",
          "major_expenditures",
          "reputationally_sensitive_communication"
        ],
        "conditions": []
      }
    },
    "triggers": {
      "red_keywords": [
        "contract",
        "agreement",
        "terms and conditions",
        "attorney",
        "counsel",
        "lawsuit",
        "litigation",
        "dispute",
        "claim",
        "fda",
        "regulatory",
        "compliance violation",
        "investor",
        "cap table",
        "fundraise",
        "term sheet",
        "offer letter",
        "termination",
        "severance",
        "salary",
        "equity",
        "nda",
        "indemnif",
        "liability",
        "health claim",
        "clinical",
        "efficacy"
      ],
      "red_when_amount_above": 25000,
      "yellow_keywords": [
        "pricing",
        "quote",
        "rate card",
        "proposal",
        "negotiat",
        "discount",
        "purchase order",
        "invoice",
        "payment terms",
        "deadline change",
        "scope"
      ],
      "yellow_when_amount_above": 1000,
      "yellow_when_new_contact": true
    },
    "approvers": {
      "default": "adi",
      "by_business_area": {
        "operations": "mike",
        "technology": "mike",
        "finance": "adi",
        "legal": "adi",
        "people": "adi"
      },
      "ceo_approval_required_above": 5000
    },
    "audit": {
      "log_all_actions": true,
      "require_reversibility": true,
      "retain_drafts_days": 90
    }
  },
  "followupRules": {
    "defaults": {
      "business_days_only": true,
      "timezone": "America/New_York"
    },
    "cadence": {
      "external": {
        "first_followup_business_days": 3,
        "second_followup_business_days": 7,
        "escalate_business_days": 12,
        "max_followups": 4
      },
      "internal": {
        "first_followup_business_days": 2,
        "second_followup_business_days": 4,
        "escalate_business_days": 7,
        "max_followups": 3
      }
    },
    "by_importance": {
      "1": {
        "first_followup_business_days": 8,
        "max_followups": 2
      },
      "2": {
        "first_followup_business_days": 5
      },
      "3": {},
      "4": {
        "first_followup_business_days": 2,
        "max_followups": 5
      },
      "5": {
        "first_followup_business_days": 1,
        "max_followups": 6
      }
    },
    "follow_up_ownership": {
      "resolution_order": [
        "organization.execution_tracker",
        "task.project_manager",
        "organization.relationship_owner",
        "task.primary_owner"
      ],
      "never_send_on_behalf_of_others": true,
      "notification_pattern": "{counterparty} owes {item}. {days} business days outstanding.\nDraft follow-up for {relationship_owner} is ready.\n"
    },
    "escalation": {
      "to_ceo_when": [
        {
          "importance_gte": 4
        },
        {
          "blocks_other_tasks": true
        },
        {
          "overdue_business_days_gte": 10
        },
        {
          "value_at_stake_above": 10000
        }
      ],
      "suppress_repeat_days": 3
    },
    "resolution": {
      "auto_resolve_on_reply": true,
      "auto_resolve_confidence": 0.8,
      "require_human_confirmation_when": [
        {
          "value_at_stake_above": 10000
        },
        {
          "approval_class": "RED"
        },
        {
          "importance_gte": 5
        }
      ],
      "stale_close_business_days": 45,
      "stale_close_action": "needs_review"
    }
  },
  "aiRouting": {
    "defaults": {
      "provider": "anthropic",
      "max_retries": 1,
      "timeout_ms": 60000,
      "persist_all_interpretations": true
    },
    "models": {
      "fast": "claude-haiku-4-5-20251001",
      "balanced": "claude-sonnet-5",
      "deep": "claude-opus-5"
    },
    "tasks": {
      "email_triage": {
        "model": "fast",
        "prompt": "email-classification/triage",
        "prompt_version": "1.0.0",
        "max_tokens": 1024,
        "description": "Is this even worth interpreting? Runs before any expensive call."
      },
      "email_classification": {
        "model": "balanced",
        "prompt": "email-classification/classify",
        "prompt_version": "1.0.0",
        "max_tokens": 2048
      },
      "people_discovery": {
        "model": "fast",
        "prompt": "people-discovery/identify",
        "prompt_version": "1.0.0",
        "max_tokens": 1024
      },
      "commitment_extraction": {
        "model": "balanced",
        "prompt": "commitment-extraction/extract",
        "prompt_version": "1.0.0",
        "max_tokens": 2048
      },
      "owner_routing": {
        "model": "balanced",
        "prompt": "owner-routing/route",
        "prompt_version": "1.0.0",
        "max_tokens": 1536,
        "description": "Deterministic scoring runs first; AI resolves ties and writes the reason."
      },
      "meeting_analysis": {
        "model": "deep",
        "prompt": "meeting-analysis/analyze",
        "prompt_version": "1.0.0",
        "max_tokens": 4096,
        "description": "Zoom attribution is evidence, not truth -- this needs real judgment."
      },
      "priority_review": {
        "model": "deep",
        "prompt": "priority-review/portfolio",
        "prompt_version": "1.0.0",
        "max_tokens": 4096,
        "description": "Looks at the whole portfolio, not one task at a time."
      },
      "email_drafting": {
        "model": "deep",
        "prompt": "email-drafting/draft",
        "prompt_version": "1.0.0",
        "max_tokens": 2048
      },
      "daily_brief": {
        "model": "deep",
        "prompt": "daily-brief/compose",
        "prompt_version": "1.0.0",
        "max_tokens": 4096
      },
      "completion_detection": {
        "model": "fast",
        "prompt": "email-classification/completion",
        "prompt_version": "1.0.0",
        "max_tokens": 1024
      }
    },
    "cost_controls": {
      "short_circuit_before_ai": [
        {
          "noreply_sender": true
        },
        {
          "newsletter_headers": true
        },
        {
          "automated_receipt": true
        },
        {
          "calendar_invite_only": true
        },
        {
          "out_of_office": true
        },
        {
          "duplicate_source_id": true
        }
      ],
      "cache_stable_context": true,
      "batch_where_possible": true,
      "daily_call_budget_warn": 2000,
      "daily_call_budget_halt": 5000
    },
    "confidence_gates": {
      "create_task": 0.6,
      "auto_route": 0.45,
      "auto_complete": 0.85,
      "auto_merge": 0.8,
      "send_anything": 0.95
    }
  },
  "financeRules": {
    "books": {
      "close_day_of_month": 10,
      "open_month": {
        "revenue_usable": true,
        "expenses_usable": false,
        "profit_usable": false,
        "flag_uncategorized": false
      },
      "closed_month": {
        "revenue_usable": true,
        "expenses_usable": true,
        "profit_usable": true,
        "flag_uncategorized": true
      }
    },
    "live_commerce": {
      "independent_of_books_close": true
    },
    "thresholds": {
      "min_comparison_base": 1000,
      "uncategorized_floor": 1000
    }
  }
} as SystemConfig;
