#!/usr/bin/env tsx
/**
 * Build the browser bundle of the decision engine.
 *
 * The Command Center UI runs the SAME routing, priority and matching code the
 * test suite exercises — not a reimplementation. Two things make that possible:
 *
 *  1. config/*.yaml is serialized to JSON at build time, so the browser never
 *     parses YAML and the UI cannot drift from the committed configuration.
 *  2. The engine modules are pure functions over plain data, with no database
 *     or filesystem access, so they bundle without shims.
 *
 * Output: dist/browser/engine.js  (IIFE, global `OS120`)
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import * as esbuild from 'esbuild';
import { loadConfig, REPO_ROOT } from '../src/config/load.js';

const OUT_DIR = join(REPO_ROOT, 'dist', 'browser');
mkdirSync(OUT_DIR, { recursive: true });

// --- 1. Freeze config into a TypeScript module -----------------------------
const config = loadConfig(undefined, { force: true });
const generated = join(REPO_ROOT, 'src', 'browser', 'config.generated.ts');
writeFileSync(
  generated,
  `/* GENERATED by scripts/build-browser-engine.ts — do not edit.\n` +
  ` * Serialized from config/*.yaml so the browser bundle cannot drift from\n` +
  ` * the committed configuration. Re-run the build after any config change. */\n` +
  `import type { SystemConfig } from '../schemas/config.js';\n\n` +
  `export const CONFIG: SystemConfig = ${JSON.stringify(config, null, 2)} as SystemConfig;\n`,
  'utf8',
);

// --- 2. Bundle -------------------------------------------------------------
const result = await esbuild.build({
  entryPoints: [join(REPO_ROOT, 'src', 'browser', 'engine.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'OS120',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  outfile: join(OUT_DIR, 'engine.js'),
  legalComments: 'none',
  metafile: true,
});

const bytes = readFileSync(join(OUT_DIR, 'engine.js')).length;
console.log(`✓ engine bundled — ${(bytes / 1024).toFixed(1)} KB`);

const inputs = Object.entries(result.metafile.inputs)
  .sort((a, b) => b[1].bytes - a[1].bytes)
  .slice(0, 5);
for (const [file, info] of inputs) {
  console.log(`    ${(info.bytes / 1024).toFixed(1).padStart(7)} KB  ${file}`);
}
